[package]
name = "wwrap"
version = "0.1.0"
authors = ["Vasya Novikov <n1dr+cm3513git@ya.ru>"]
edition = "2018"

[dependencies]
libc = "0.2.42"

[profile.release]
# To bulid with musl: cargo build --target=x86_64-unknown-linux-musl --release
lto = true
#rpath = false
